name: kavine
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  minio: 
    image: bitnami/minio:latest
    container_name: minio
    ports: 
      - '9000:9000'   # S3 API endpoint
      - '9001:9001' # Web console
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    
volumes:
  minio_data: